server:
  port: 10000
  servlet:
    context-path: /grid-server

node-properties:
  execute-method: /exec
  ping-method: /ping
  directory: subtaskJar
  jar-file-name: jar-file.jar
  builder-url: http://localhost:9500
  send-result-method: /api/sendSubtaskResult
